apiVersion: v1
kind: Service
metadata:
  name: task-tracker-api
  namespace: task-tracker
spec:
  selector:
    app: task-tracker-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP