apiVersion: v1
kind: Service
metadata:
  name: task-tracker-api
  labels:
    {{- include "task-tracker-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: task-tracker-api
  ports:
    - port: 80
      targetPort: {{ .Values.api.port }}
  type: ClusterIP