apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-api
  labels:
    {{- include "task-tracker-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: task-tracker-api
  template:
    metadata:
      labels:
        app: task-tracker-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: postgres-secret
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 15