apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    {{- include "task-tracker-chart.labels" . | nindent 4 }}
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgres.database | quote }}
  PORT: {{ .Values.api.port | quote }}