apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-allow-api
  labels:
    {{- include "task-tracker-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: task-tracker-api
      ports:
        - protocol: TCP
          port: 5432